name: package_arch_project
description: Bytebank - Um projeto Alura agora no Flutter
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  google_fonts: ^6.2.1
  intl: ^0.20.2
  bytebank_balance:
    git:
      url: https://github.com/cleitoncunha04/bytebank_balance.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/
    - assets/pixels/
    - assets/illustrations/

flutter_native_splash:
  color: "#000000"
  image: assets/favicon-64.png
  android_12:
    color: "#000000"
    icon_background_color: "#000000"
    image: assets/favicon-1152.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/favicon-64.png"
  min_sdk_android: 21