name: mvc_project
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  http: ^1.2.2
  sqflite: ^2.4.1
  path: ^1.9.0
  flutter_native_splash: ^2.4.4
  carousel_slider: ^5.0.0
  lottie: ^3.2.0
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/lottie/
  fonts:
  - family: Bigelow Rules
    fonts:
      - asset: assets/fonts/BigelowRules-Regular.ttf

flutter_native_splash:
  color: "#4D1245"
  image: "assets/images/grimorio_1152.png"
  android_12:
    color: "#4D1245"
    icon_background_color: "#4D1245"
    image: assets/images/grimorio_1152.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/grimorio.png"
  min_sdk_android: 21